import Head from 'next/head'
import {Inter} from '@next/font/google'
import React from "react";
import {PosterBuilder} from "@/components/containers/PosterBuilder";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Editor - Posterly</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <PosterBuilder/>
            </main>
        </>
    )
}
